### PR TITLE
Fix timeout refund on an unlimited channel

### LINKED ISSUE #4822: Refund on an unlimited channel was rejected due to the rate limit
On an unlimited-rate channel, any mint/unescrow should work. However, the IBC refund when the timeout on the unlimited channel didn't work on the Namada housefire.

```
vps_result: VpsResult { accepted_vps: {Internal Multitoken: tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv, Implicit: tnam1qq4hsdxkwvz8ld0kvdpsmc7fk8jjy2cnycxg2msu}, rejected_vps: {Internal IBC: tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4}, errors: [(Internal IBC: tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4, "Native VP error: IBC rate limit: Transfer exceeding the mint limit is not allowed: Mint limit 0, minted amount 3839264534473020")],
```

It is caused by the IBC message type `Timeout` not being considered in the rate limit check.

### PR DESCRIPTION
**Pull request by yito88**
## Describe your changes
closes #4822

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes
- [ ] If this PR requires changes to the docs or specs, a corresponding PR is opened in the `namada-docs` repo
    - Relevant PR if applies: 
- [ ] If this PR affects services such as `namada-indexer` or `namada-masp-indexer`, a corresponding PR is opened in that repo
    - Relevant PR if applies:

### CODE REVIEW

File: crates/ibc/src/vp/mod.rs [hunk 1]
```diff
@@ -400,13 +400,15 @@ where
...
                     Some(&msg.packet.chan_id_on_b)
-                } else {
-                    None
                 }
-            }
+                MsgEnvelope::Packet(PacketMsg::Timeout(msg)) => {
+                    Some(&msg.packet.chan_id_on_a)
+                }
+                _ => None,
+            },
```
Comment (sug0) [inline crates/ibc/src/vp/mod.rs:411]: would there also be an issue with ack errors? on [`PacketMsg::Ack`](https://docs.rs/ibc/latest/ibc/core/channel/types/msgs/enum.PacketMsg.html#variant.Ack)
